package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestingDev001'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestingDev001")) {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                branchFilter = """
                    +pr: draft=false
                    -:refs/heads/main
                    -:<default>
                """.trimIndent()
            }
        }
        trigger1.apply {
            branchFilter = """
                +pr: draft=false
                +:<default>
            """.trimIndent()

        }
    }
}
