package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "PROJECT_EXT_4"
                displayName = "terranigma-solutions/liquid_earth_python_sdk"
                repositoryURL = "https://github.com/terranigma-solutions/liquid_earth_python_sdk"
                param("tokenId", "")
            }
        }
        feature1.apply {
        }
    }
}
