package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComTerranigmaSolutionsLiquidEarthPythonSdkRefsHeadsMain1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComTerranigmaSolutionsLiquidEarthPythonSdkRefsHeadsMain1")
    name = "https://github.com/terranigma-solutions/liquid_earth_python_sdk#refs/heads/main (1)"
    url = "https://github.com/terranigma-solutions/liquid_earth_python_sdk"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "Leguark"
        password = "credentialsJSON:4df4bdb0-1278-4834-a702-18ae3a286003"
    }
}))

